name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # Need write access to create releases
  id-token: write

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: |
          pnpm run check
          pnpm run type-check

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish  # Wait for npm publish to succeed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## 📦 Installation
            ```bash
            npm install github-typescript-utils@${{ github.ref_name }}
            # or
            pnpm add github-typescript-utils@${{ github.ref_name }}
            ```

            ## 📋 Full Changelog
            See below for auto-generated release notes.
